### ISSUE TITLE
Do not wait for full page load

### ISSUE THREAD

**Issue by frankred** [baudehlo/node-phantom-simple#101]
Building a crawler bot: I have some websites that do not stop loading (very strange). Is it somehow possible to eval things on the page anyways?

Here is an example page. Due to privacy reasons run this in your browser js console to get the example url: ```atob("aHR0cDovL2Z1bmFuZHByb2ZpdC5vcmcv")```.

**Comment by puzrin** [comment]
Is this problem driver-specific? What happens if you run similar scrip in phantom directly.

**Comment by puzrin** [comment]
Closing - timed out.
