### ISSUE TITLE
Cannot read property 'createPage' of undefined - Docker container

### ISSUE THREAD

**Issue by alessandroprioni** [baudehlo/node-phantom-simple#104]
Hi, I can't run node-phantom-simple inside a Docker container. Here is my Dockerfile and docker-compose.yml: https://gist.github.com/alessandroprioni/e81ac854c761761ddb9a

Here is the error I get: 

root@5a0f60ae5666:/usr/src/app# node test.js 
/usr/src/app/test.js:4
  return browser.createPage(function (err, page) {
                ^

TypeError: Cannot read property 'createPage' of undefined
    at /usr/src/app/test.js:4:17
    at /usr/src/app/node_modules/node-phantom-simple/node-phantom-simple.js:277:7
    at /usr/src/app/node_modules/node-phantom-simple/node-phantom-simple.js:245:13
    at ChildProcess.exithandler (child_process.js:210:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

If I try to run ´phantomjs´ directly from the console it works.

Anyone knows how to help?

Thanks!

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple#createoptions-callback Make sure to pass proper path to `create()`, if it can't be found by default.

For example, `{ path: require('phantomjs').path }`

**Comment by alessandroprioni** [comment]
Here is the code:
driver.create({ path: require('phantomjs').path }, function (err, browser) {

and if I run `require('phantomjs').path` from node I get:
/usr/src/app/node_modules/phantomjs/lib/phantom/bin/phantomjs

and it works.

**Comment by puzrin** [comment]
Closing?

**Comment by alessandroprioni** [comment]
It still doesn't work from Node :)

**Comment by puzrin** [comment]
Hm... you need to trace code before this line https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L245 in your environment. Probably it has no `ss` and `netstat` tools. As alternative - use slimerjs, it should work because does not need those kludges.

**Comment by alessandroprioni** [comment]
I have both `ss` and `netstat`. Here is the error I get:

`{ [HeadlessError: Error executing command to extract phantom ports: Error: Command failed: /bin/sh -c ss -nlp | grep "[,=]2046," || netstat -nlp | grep "[[:space:]]2046/"
]
  name: 'HeadlessError',
  message: 'Error executing command to extract phantom ports: Error: Command failed: /bin/sh -c ss -nlp | grep "[,=]2046," || netstat -nlp | grep "[[:space:]]2046/"\n' }
/usr/src/app/test.js:7
  browser.createPage(function (err, page) {
         ^

TypeError: Cannot read property 'createPage' of undefined`

**Comment by puzrin** [comment]
It says it fail to execute `/bin/sh -c > ss -nlp | grep "[,=]2046," || netstat -nlp | grep "[[:space:]]2046/"`. I don't know why it happens in your env. But as soon as you can fix it, driver will work.

**Comment by alessandroprioni** [comment]
if I run that command directly in the console I get:
`/bin/sh: 0: Illegal option -p`

**Comment by puzrin** [comment]
I guess, that's `-nlp` opts. Dig into `man`, probably options was changed in new versions. Also you can cut `ss -nlp | grep "[,=]2046," ||` or `|| netstat -nlp | grep "[[:space:]]2046/"` to locate exact error src.

Idea was to try available tools until success. Modern distros have `ss`, old ones have `netstat`. Last change in this line was discussed in https://github.com/baudehlo/node-phantom-simple/issues/76#issuecomment-154423121 and below. I'm not strong in shell programming. If you have ideas how to improve those command - let me know.

**Comment by puzrin** [comment]
@alessandroprioni did you solved your problem?

**Comment by puzrin** [comment]
I had no chance to play with docker, but this line is suspicious https://gist.github.com/alessandroprioni/e81ac854c761761ddb9a#file-docker-compose-yml-L2. Do you try to use busybox with built-in commands? Those have reduced functionality sometime. If that's true, then i see 2 posiible ways:

- use another base image, with full ss/netstat available
- investigate alternative commands for busybox

**Comment by puzrin** [comment]
http://serverfault.com/questions/219984/busybox-netstat-no-p install normal netstat/ss, instead the one from busybox.
