### ISSUE TITLE
SlimerJS warnings cause HeadlessError

### ISSUE THREAD

**Issue by awlayton** [baudehlo/node-phantom-simple#105]
When passing options that are not yet supported to slimer (e.g., `--ignore-ssl-errors`), a `HeadlessError` is thrown with a message about said argument (e.g., `Unexpected output from PhantomJS: --ignore-ssl-errors not supported yet`).

This was pointed out by @w33ble in johntitus/node-horseman#99.

However, these are not actual errors and slimer is able to run just fine with these arguments on the command line. It would be nice if node-phantom-simple would still work in this situation.

**Comment by puzrin** [comment]
I don't like this idea. If option is passed, but ignored, that's not good.

**Comment by puzrin** [comment]
Close - rejected, sorry.
