### ISSUE TITLE
Error 403: Directory Listing Denied kills PhantomJS instance

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#109]
Getting this issue randomly. Does anyone know what could be the reason for this error?

Unhandled rejection SyntaxError: Unexpected token E
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:459:28)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
Unhandled rejection SyntaxError: Unexpected token E
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:459:28)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

**Comment by mato75** [comment]
Still getting this issue, even after an if statement, that checks if data is present.

**Comment by mato75** [comment]
Ok, found the problem. Issue is in parsing data, because data is this:

```
{ [HeadlessError: Error parsing JSON from phantom: SyntaxError: Unexpected token E
Data from phantom was: Error 403: Directory Listing Denied
Directory listing denied]
  name: 'HeadlessError',
  message: 'Error parsing JSON from phantom: SyntaxError: Unexpected token E\nData from phantom was: Error 403: Directory Listing Denied\nDirectory listing denied' }
```

**Comment by mato75** [comment]
This error also kills PhantomJS instance, which is not ok.

**Comment by mato75** [comment]
In bridge.js, watchdog_clear should not kill phantomjs instance, but close the page and if there is no page opened, then close the instance.

**Comment by ohenepee** [comment]
Please what is causing the ` 403 Directory Listing Denied` and can it be solved?

As to what causes it is unknown to me, but I am aware it comes from the Mongoose server... is the server buggy? Or is there some timing issues that need to be addressed (as in rapid repetitive / intermittent launching of phantomjs executable)

**Comment by ohenepee** [comment]
I found a way to reproduce the bug... please run the code for 20 mins and you'll see the bug pop up.
I ran mine on a VPS with Ubuntu Server 14.04 LTS 64-bit

```
const Horseman = require("node-horseman");

var browserIsReady = true;

function reachPage() {
  
  var horseman = new Horseman();
  console.log("Starting...");
  
  horseman
  .viewport(800, 600)
  .open("https://www.facebook.com/bbcnews")
  .status()
  .then(function (status) {
    if (Number(status) != 200) {
      console.log("Couldn't load page, trying again...");
      return horseman.close();
    }
  })
  .wait(1e4)
  .log("Stepping out...") // prints out the durl
  .wait(3e3)
  .finally(function() {
    horseman.close();
    setTimeout(reachPage, 3e3);
    return
  });
  
}

reachPage();
```

![2016-03-10-111941_659x314_scrot](https://cloud.githubusercontent.com/assets/15159487/13668308/d75e705a-e6b3-11e5-89d1-a597fa63ea65.png)

**Comment by sbryfcz** [comment]
Any status on this bug? Hitting the same issue.

**Comment by baudehlo** [comment]
This doesn't seem like a bug - more that the provider is throttling you, no?

**Comment by ohenepee** [comment]
No!! What do you even understand or mean by THROTTLING? That photo above is from a 100Mbps link VPS (downloads speeds maxes past 10MB/s)... so no it has nothing to do with throttling!

**Comment by baudehlo** [comment]
I mean Facebook throttling you for hitting the page over and over.

**Comment by sbryfcz** [comment]
Regardless, I would expect Phantom to crash, just as I wouldnt expect a browser to crash. But I'm admittedly new to Phantom. Maybe I'm missing a better practice.

**Comment by tsirolnik** [comment]
The bug is still happening - Happened to me while using node-horseman

**Comment by ohenepee** [comment]
Actually after a few production runs, it turns out that Phantom crashes as a result of CPU max'ing... when it HITS 100% CPU usage and still needs more CPU power to do what it wants to do... simple solution; get a faster computer and prove me wrong

**Comment by tbouchnafa** [comment]
+1

**Comment by hibearpanda** [comment]
+1

**Comment by ohenepee** [comment]
This is an issue with PhantomJS itself.. so you guys will have to base with this annoying bug. You can simply save state and repeat the activity as a workaround
