### ISSUE TITLE
Can node-phantom-simple handle multiple phantomjs instances

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#111]
As soon as I have multiple phantomjs instances, I am starting to get issues of PhantomJS kills. Were there any stress tests of multiple phantomjs instances running at one time?

**Comment by baudehlo** [comment]
You must be doing something wrong, because it was specifically written for
this use-case.

**Comment by mato75** [comment]
I am getting this issue all the time and there is no more info then this:

       [SyntaxError: Unexpected token E]

And after this, all hell breaks lose.

**Comment by mato75** [comment]
Ok, found the problem. Issue is in parsing data, because data is this:

```
{ [HeadlessError: Error parsing JSON from phantom: SyntaxError: Unexpected token E
Data from phantom was: Error 403: Directory Listing Denied
Directory listing denied]
  name: 'HeadlessError',
  message: 'Error parsing JSON from phantom: SyntaxError: Unexpected token E\nData from phantom was: Error 403: Directory Listing Denied\nDirectory listing denied' }
```

**Comment by ohenepee** [comment]
Why was this ISSUE closed? The problem hasn't yet been solved or did @mato75 find a solution?

**Comment by mato75** [comment]
Yes, will write my solution, but don't have time right now.

**Comment by tbouchnafa** [comment]
any news on this bug? same here +1

**Comment by awlayton** [comment]
The "bug" for this issue never actually existed @tbouchnafa. node-phantom-simple *does* work with multiple instances.

**Comment by rubenstolk** [comment]
@puppeteer701 what was your solution?
