### ISSUE TITLE
page.onResourceRequested is undefined

### ISSUE THREAD

**Issue by abhilashsajeev** [baudehlo/node-phantom-simple#116]
Some cases require use of onResourceRequested, onError, onConsoleMessage methods of phantomjs-node. How this is implemented in this library?

**Comment by Reewr** [comment]
Whenever PhantomJS sends an event and node-phantom-simple recieves it through polling, node-phantom-simple will call whichever function that is correct for that event, if the function exists. If you want to use `onResourceRequested`, you will need to do something along the lines of:

```js
// create driver, page etc.
page.onResourceRequested = function(id, method, url, time, headers) {
  // do something here
};
```
Keep in mind that all of these events are asynchronous events. This mean you won't be able to return values in cases for `onConfirm` or `onPrompt`. To return values in these instances, you will need to use:

```js
page.setFn('onConfirm', function(message) {
  // this function won't have access to the outer-scope
  return message === 'yes';
});
```

**Comment by abhilashsajeev** [comment]
Also how to add multiple parameters? 
```javascript
phantom.create({ parameters: { 'ignore-ssl-errors': 'yes' ,path:require('phantomjs2.0').path} }, function (err, ph) {
// do stuff
}
```

does not seem to work

**Comment by puzrin** [comment]
```js
{
  path: ...
  parameters: { ... }
}
```

you have wrong options structure.

**Comment by abhilashsajeev** [comment]
does that takes a *port * parameter?

**Comment by puzrin** [comment]
No. Port is dynamic every time you create new phantom instance. Search in old issues, that was discussed.

https://github.com/baudehlo/node-phantom-simple/blob/v1.2.0/bridge.js#L52

**Comment by puzrin** [comment]
Can we close this issue?

**Comment by abhilashsajeev** [comment]
Yeah. I figured it out.
