### ISSUE TITLE
watchdog timeout kills phantomjs instance

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#124]
This timeout is not ok, because when running multiple pages, and one page is not getting any response, phantomjs is killed. Watchdog should be by page and not by phantomjs instance.

**Comment by puzrin** [comment]
1. Watchdog is to detect phantomjs crashes and incorrect closes. It will be useless for single page.
2. Phantomjs itself has many problems with memory, and i've seen recommendation from developpers to create new instances for different pages, instead of reuse the same.

We could allow to set custom watchdog timeout, if there are real cases when page is loaded longer than 30 sec. Or rewrite bridge queue to allow pings while open is in progress. But need to understand first if that's really required.

**Comment by mato75** [comment]
Hm, I am creating multiple tabs inside a phantomjs instance and I am only closing the phantomjs instance when all tabs are closed.

I added a timeout of 15s, if page is not created, return error (unfortunately this happens a lot).

Do you know any progress when it comes to memory issues with phantomjs instance.

**Comment by puzrin** [comment]
There are no noiceable progress about memory issues. And 1.9 is more stable than 2.x. We had a lot of problem with failed tests on travis, and finally migrated to slimerjs. It doesn't crash as much as phantom, but more slow and can freeze sometime to 10-15 sec on page open when not enougth memory.

Anyway, i recommend to replace tabs use to independent instances.

**Comment by mato75** [comment]
We have to use 2.x version, because we are searching for dom elements inside iframes, and with 2.x we actually find elements, where when using 1.9, we in more cases didn't find anything.

**Comment by puzrin** [comment]
It's up to you. I just shared experience. Please, decide if this issue is really needed or can be closed.

**Comment by baudehlo** [comment]
Can share a similar experience - we just opened a new phantom instance for
everything. Memory is cheap, crashes that take down all concurrent requests
are painful.

**Comment by awlayton** [comment]
I also try to use one page per instance, but sometimes a page causes another page to be opened (e.g., when a link is clicked). It would be nice to have a way to spend an extended period working with that child page and not die because the parent page timed out.

**Comment by baudehlo** [comment]
In those scenarios can you not re-write the tag or hijack window.open?
That's what I used to do.

**Comment by awlayton** [comment]
Never mind I misunderstood I think. I thought it timed out if a given page was not used for the timeout period, but looking at the code I see the timeout is for the phantom instance not receive requests for any pages.

**Comment by puzrin** [comment]
It solves 2 cases:

1. Command is executed too long (= fatal problems with tab, exit phantom)
2. Node.js process crashed without close phantom (= autoexit after timeout)

**Comment by puzrin** [comment]
Close - initial request is not relevant, and no details added to prove that existing behaviour should be changed.
