### ISSUE TITLE
Error creating a page

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#128]
{ [HeadlessError: Request() error evaluating createPage() call: Error: connect ECONNREFUSED 127.0.0.1:34574]
  name: 'HeadlessError',
  message: 'Request() error evaluating createPage() call: Error: connect ECONNREFUSED 127.0.0.1:34574' }

This happens sometimes.

**Comment by awlayton** [comment]
I need more to go on than "it happens sometimes".

**Comment by puzrin** [comment]
Closing. That does not means it a bug, and here are no details at all.
