### ISSUE TITLE
.open return status undefined/error

### ISSUE THREAD

**Issue by mato75** [baudehlo/node-phantom-simple#130]
This is an error I get sometimes, when used with SlimerJS, but when used with PhantomJS, it returns undefined error.

I dont know what causes this, but heavy usage of browser is the main factor probably.

{ [HeadlessError: JSON parse on req with data: <html>                    <head><title>500 Internal Server Error</title></head>                    <body>                      <h1>500 Internal Server Error</h1>                      <p>Something's broken in this server and                        needs to be fixed.</p>                    </body>                  </html>, error: SyntaxError: Unexpected token <, method: open]
  name: 'HeadlessError',
  message: 'JSON parse on req with data: <html>                    <head><title>500 Internal Server Error</title></head>                    <body>                      <h1>500 Internal Server Error</h1>                      <p>Something\'s broken in this server and                        needs to be fixed.</p>                    </body>                  </html>, error: SyntaxError: Unexpected token <, method: open' }
5710ff73fb081dc91db82a83_5710f10d9b61f13d06815732 ===> Page Error: {"name":"HeadlessError","message":"JSON parse on req with data: <html>                    <head><title>500 Internal Server Error</title></head>                    <body>                      <h1>500 Internal Server Error</h1>                      <p>Something's broken in this server and                        needs to be fixed.</p>                    </body>                  </html>, error: SyntaxError: Unexpected token <, method: open"}

**Comment by puzrin** [comment]
Please, stop creating useless issues here.
