### ISSUE TITLE
Please add more description for page.evaluate()

### ISSUE THREAD

**Issue by edwardfung123** [baudehlo/node-phantom-simple#3]
EDIT: sorry. I didn't read the example carefully.

Could you add a document for page.evaluate since it is quite different from the phantomjs's page.evaluate(). 

I find that by experiment and read the source code.

1. It is async. var ret = page.evalute(fn, arg1, arg2, ...); the page.evaluate() is "returned" immediately before fn() is executed. 

2. your page.evaluate() takes an extra parameters "cb" page.evaluate(fn, cb, arg1, arg2...).

**Comment by puzrin** [comment]
Solved by https://github.com/baudehlo/node-phantom-simple/issues/39 . Callbacks now are last params always and should not cause confusion.
