### ISSUE TITLE
onFilePicker

### ISSUE THREAD

**Issue by ryanstout** [baudehlo/node-phantom-simple#34]
Is onFilePicker supported.  I tried it and I didn't get the callback.

Thanks!

**Comment by puzrin** [comment]
It crashes often and in inpredictable way. The only thing i can advise - if you did a lot of operations before, create a new phantom instance for upload-related use-case.

I think this sould be asked in phantomjs repo. If you can provide example, working in phantomjs directly, but broken via this driver - please create a new ticket with details how to reproduce.
