### ISSUE TITLE
Node and callback as last argument

### ISSUE THREAD

**Issue by seebees** [baudehlo/node-phantom-simple#39]
There are a lot of functions here that do not honor this paradigm.  I can start giving you PR that would "fix" these issues, but I don't know if you are even interested.  As it might break current functionality.

What do you think?

for example:
https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L238-L242

This would be better done IMO

```javascript
 {evaluate: function (fn) {
    var extra_args = []
      , cb = false
    if (arguments.length > 1) {
      // convert arguments into a reall boy
      var extra_args = Array.prototype.slice.call(arguments, 1)
      // grab the end to check if it's a callback
      var cb = extra_args.pop()
      if (typeof cb !== 'function') {
        // not a callback?  put it back...
        extra_args.push(cb)
        cb = false
      }
      // console.log("Extra args: " + extra_args);
    }
    request_queue
      .push([[id
            , 'evaluate'
            , fn.toString()].concat(extra_args)
            , callbackOrDummy(cb, poll_func)]);
  }}
```

**Comment by baudehlo** [comment]
I don't understand. The last arg is enforced to be a callback, not
optional... evaluate can just take extra params that get passed into the
call.

Making the callback optional breaks things like async.

**Comment by seebees** [comment]
The callback is not the last argument.  The way you have it is like this

`page.evaluate (inPhantomfunc, callback, some, optional, args)`

What I wrote would allow

`page.evaluate (inPhantomfunc, any, number, of, optional, args, callback)`

This is useful when writing integration.  The callback can be added by the implementer.

**Comment by baudehlo** [comment]
Oh I see. Hmm.

It would probably be painful to break this API for some people. But you're
right the callback should be the last arg. Might be time to bump the major
version number.

**Comment by seebees** [comment]
Ya. It would break a few things ;). I'll look around for stuff and throw up a PR and let you decided.

**Comment by seebees** [comment]
@baudehlo take a look at #40... There were 3 functions that would change....

**Comment by puzrin** [comment]
`create` & `waitForSelector` can be fixed in compatible way.

`evaluate` can't . I think, it's better to fix 2 methods and wait `evaluate` intact.

**Comment by seebees** [comment]
@puzrin Why can't `evaluate ` be fixed in a compatible way?

**Comment by puzrin** [comment]
At first glance, it's dangerous to rely on expectation, that passed param can not a function. That's ok in 99.9% of cases, but not in 100%.

I'm organizing 1.3.0 window changes (there are enougth to do). IMHO it's better to fix as much as possible, and leave more destructive things for 2.0.0.

**Comment by puzrin** [comment]
I digged sources and thinked again about compatibility. It seems more safe for community to release 2.0.0 due other changes (`.exit()` will be much better with callback). While i'll try to keep full transparency with old signature, i don't like to risk with fuckuping packages, depending on this one with `^1.0.0` in dependencies.

So, it will be safe to do this things:

1. Use hack to detect callback position in evaluate (suppose, that users ~~are not idiots~~ will not pass functions as params of evaluated one).
2. Add deprecation messages for old signature calls (`util.deprecate`).
