### ISSUE TITLE
meet phantom stdout: TypeError: undefined is not an object (evaluating 'phantom.args[0]')

### ISSUE THREAD

**Issue by tlightsky** [baudehlo/node-phantom-simple#41]
node_modules/node-phantom/bridge.js:3 in global code

**Comment by tlightsky** [comment]
https://github.com/sgentle/phantomjs-node/pull/209
this might be helpful

**Comment by baudehlo** [comment]
You've submitted this bug to the wrong module. node-phantom-simple doesn't use phantom.args
