### ISSUE TITLE
Retrieve a list of cookies?

### ISSUE THREAD

**Issue by johntitus** [baudehlo/node-phantom-simple#42]
Is there a way to retrieve a list of cookies that PhantomJS has? Similar to http://phantomjs.org/api/webpage/property/cookies.html

**Comment by baudehlo** [comment]
Does `page.getProperty('cookies')` work?

**Comment by johntitus** [comment]
Using `page.get` (I think getProperty is internal only?) doesn't seem to.

```js
var phantom = require('node-phantom-simple');

var cookie = {
	name : "test",
	value : "cookie",
	path : "/",
	domain : "httpbin.org"
};
phantom.create(function(err,ph) {
	ph.createPage(function(err,page) {
		page.addCookie( cookie, function(err){
			if ( err ) throw err;
			page.open("http://httpbin.org/", function(err,status) {
	      		page.get('cookies', function( cookies ){
	      			console.log(cookies);
	      			ph.exit();
	      		});	      		
	      	});
	    });    	
    });
});
```

The result is just `null`.

**Comment by puzrin** [comment]
page get/set [works](https://github.com/nodeca/navit/blob/master/lib/get.js#L244-L259)

- get example https://github.com/nodeca/navit/blob/master/lib/get.js#L244-L259
- set example https://github.com/nodeca/navit/blob/master/lib/set.js#L16-L59

Is this issue still actual or can be closed?

**Comment by johntitus** [comment]
I figured out the problem, and I think the issue can be closed.

In the example above, the line
`page.get('cookies', function( cookies ){`

should instead read
`page.get('cookies', function( err, cookies ){`
