### ISSUE TITLE
Falsy values are returned as null

### ISSUE THREAD

**Issue by johntitus** [baudehlo/node-phantom-simple#43]
Falsy values, such as emtpy string and `false`, get returned as `null`.  For example, the following code returns expected values, because it's wrapped in an object:

```js
var phantom = require('node-phantom-simple');

phantom.create(function(err,ph) {
  	ph.createPage(function(err,page) {
    	page.open("http://www.google.com", function(err,status) {
      		console.log("opened site? ", status);
      		page.includeJs('http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js', function(err) {
		       	page.evaluate( function(){
	        		return {
	        			count : $('input[name="q"]').length,
	        			emtpyString : $('input[name="q"]').val(),
	        			bool : $('input[name="q"]').is('a')
	        		};
	        	}, function( err, result ){
	        		console.log( result );
	        		ph.exit();
	        	});
		    });
      	});
    });
});
```

The output is:
`{ bool: false, count: 1, emtpyString: '' }`

However, if we change the inner `page.evaluate` to this, where it returns just the `emptyString`:

```js
              page.evaluate( function(){
	        		return $('input[name="q"]').val();
	        	}, function( err, result ){
	        		console.log( result );
	        		ph.exit();
	        	});
```

The output is `null`, when instead an empty string, ``, was expected.

The same thing occurs when returning a `false`:

```js
		       	page.evaluate( function(){
	        		return $('input[name="q"]').is('a');
	        	}, function( err, result ){
	        		console.log( result );
	        		ph.exit();
	        	});
```

Again, the output is now `null`, when a `false` was expected.

**Comment by jwarby** [comment]
+1

**Comment by johntitus** [comment]
Awsome, thanks. Is this fix going into the 1.x line, or are you targetting a 2.x line, since this looks (at just a glance) to be a breaking change?

**Comment by puzrin** [comment]
I don't like to spend time for supporting multiple branches. So, it will be 2.x.

If fact, real changes are transparent, you code will work but can show deprecation messages.

**Comment by jwarby** [comment]
Thanks for this.  `null` seems to be returned as `''` and `undefined` as `null` now though?  The other falsy values I tried worked as expected - `0`, `false` and `''`.

**Comment by puzrin** [comment]
@jwarby see https://github.com/baudehlo/node-phantom-simple#known-issues, those are phantom bugs. Slimer behave much better.

**Comment by puzrin** [comment]
Released 2.0.0, enjoy!

@johntitus I've added migration details for you https://github.com/baudehlo/node-phantom-simple#migrating-1x---2x. Should be easy.

**Comment by johntitus** [comment]
Awesome, congrats on the release!

**Comment by jwarby** [comment]
@puzrin Ah that's unfortunate!  Anyway this is much better than it was so thanks! :D
