### ISSUE TITLE
settings.userAgent has no effect

### ISSUE THREAD

**Issue by manuelbieh** [baudehlo/node-phantom-simple#45]
Two problems, not sure if I'm just stupid or node-phantom-simple fails. I tried the following gist on Windows 7 with PhantomJS 1.9.7 and node-phantom-simple 1.2.0 and on Ubuntu 12.04 with PhantomJS 1.9.8:

https://gist.github.com/manuelbieh/2d838715e4472c1f0a72

In case 1 I get no output at all. Neither the user agent nor `-- the end --`:

```
$ node ua-test
null 'success'
```

In case 2 I get output but the user agent hasn't been changed:
```
$ node ua-test
null 'success'
phantom stdout: userAgent: Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34
-- the end --
```

Can somebody help me find the error?

**Comment by manuelbieh** [comment]
Ok, I found it. Must be a bug. Adding `javascriptEnable: true` makes it work:

```
page.set('settings', {
    javascriptEnabled: true,
    userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36'
});
```

**Comment by baudehlo** [comment]
I don't think it's a bug. You need: `page.set('settings', { userAgent:
'....' })` not `page.set('settings.userAgent', '...')`.

**Comment by manuelbieh** [comment]
Ok, my mistake. But nevertheless: it doesn't work as long as you don't set `javascriptEnabled` to `true` explicitly. At least not on both machines I've tested it on.

**Comment by baudehlo** [comment]
That's just to get navigator.userAgent to work. I think. As I'm fairly sure I have this working fine in other scripts.

Anyway it's more likely to be a bug in phantom than in this module.

**Comment by denisbetsi** [comment]
It is a bug reported #49  setting any settings removes all other settings already in place.

**Comment by puzrin** [comment]
Fixed in master - dot-notation now works.
