### ISSUE TITLE
net-tools is replaced by iproute2

### ISSUE THREAD

**Issue by royalgarter** [baudehlo/node-phantom-simple#47]
In some Linux server net-tools (that provide netstat command) is deprecated and replaced by iproute2. 
Specially in Heroku Cedar-14 stack (https://devcenter.heroku.com/articles/cedar-ubuntu-packages)

Should we check to use the ss command instead? 
http://xmodulo.com/linux-tcpip-networking-net-tools-iproute2.html

**Comment by baudehlo** [comment]
Sounds like a good plan. I don't have a newer Linux install to test on. Can
you send a pull request with the relevant parameters?

**Comment by royalgarter** [comment]
Yes, I will but unfortunately, I'm a Window user and not familiar with the linux command so still trying to figure it out. I will send pull request when it's done.

**Comment by puzrin** [comment]
Note: since travis integration planned, we should check if it has `ss`, because `netstat` should be installed with separate command from [travis config](https://github.com/nodeca/navit/blob/master/.travis.yml#L6-L8) - not convenient.

**Comment by puzrin** [comment]
@royalgarter now `ss` is supported. Good news is, that net-tools install now needed anymore in travis configs https://github.com/baudehlo/node-phantom-simple/commit/c4fe80d4916528980e37b6e51ac02ef302c8e6f1

Thanks a lot for suggestion!
