### ISSUE TITLE
Assigning property "settings" overwrites the whole object

### ISSUE THREAD

**Issue by epoberezkin** [baudehlo/node-phantom-simple#49]
Possible solution - allow to assign subproperties, e.g. using https://github.com/mariocasciaro/object-path

**Comment by denisbetsi** [comment]
A very easy fix applies, hopefully it'll get merged soon.

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple/pull/28 looks more generic (closes related issues).

I tend to accept it in flavour of #50

**Comment by puzrin** [comment]
Fixed in master, dot-notation now works.
