### ISSUE TITLE
How to communicate between the nodejs and phantomjs?

### ISSUE THREAD

**Issue by edwardfung123** [baudehlo/node-phantom-simple#5]
I use setFn() to set the onLoadFinished callback of phantomjs. However, how can I pass the data back to node after the onLoadFinished callback? Is it true that the only way to do this is to listen to the ph.process.stdout 'data' event and parse the stream myself?

**Comment by puzrin** [comment]
The most often method is to evaluate script on the page and get reply from it. You can dig [sources of more high level wrappers](https://github.com/baudehlo/node-phantom-simple/issues/23#issuecomment-119362742) for working examples.
