### ISSUE TITLE
Not all page resources sent to onResourceRequested in PhantomJS

### ISSUE THREAD

**Issue by RavenHursT** [baudehlo/node-phantom-simple#51]
So I've got two different pages that I'm trying to gather all the resources requested against:

http://www.clarizen.com/work/resource-management

and

https://www.docusign.com/free/sign-anywhere

If you load both pages in chrome, you'll see in the network tab >= 4 requests to http://pixel.captora.com/img/pix.gif, passing various data in the query string for each page.

But when I try to load the same two pages in phantomJS (using node-phantom-simple bridge), in the case of the clarizen.com page, all the pix.gif calls are sent to the page.onResourceRequested callback.  But in the case of the docusign.com page, only the *first* call to the pix.gif is ever sent to the callback.

````javascript
    phantom.create(function(err, ph){
      ph.createPage(function(err, page){
        page.onResourceRequested = function(requestData){
          requestData = requestData.shift();
          console.log(requestData.url);
        };
        
        page.open([page url], function(status){
          setTimeout(function(){ page.close(); }, 10000);
        });
      });
    });
````

Obviously it's got something specifically to do w/ the docusign.com page.. but I can't, for the life of me figure out where the delta lies.  Please help?

Related SO question: http://stackoverflow.com/questions/30677596/not-all-page-resources-sent-to-onresourcerequested-in-phantomjs

**Comment by puzrin** [comment]
@RavenHursT try 2.0.0 with SlimerJS. Phantom's engine is very old and buggy.
Or  run your script in phantomjs directly, from CLI. May be your problem is not related to this driver at all.

Need more info.

**Comment by RavenHursT** [comment]
Sorry.. should've closed this a while ago.

Turns out that I just wasn't waiting long enough to see the pixel requests.  I solved it by 1) waiting for the initial page call resource to be reported in onResourceReceived() and then waited an extra 2000ms before checking the resource requests array..

Closing.

**Comment by puzrin** [comment]
Well, now only 3 tickets (+ 2 my memos) left :)

**Comment by baudehlo** [comment]
And I definitely owe you a beer if you're ever in Toronto :)
