### ISSUE TITLE
Need linter and unified coding style

### ISSUE THREAD

**Issue by puzrin** [baudehlo/node-phantom-simple#57]
@baudehlo , we are about to finish deals for 2.0.0 release window. I highly recommend to use [eslint](http://eslint.org/) with tests and unify coding style. That will be very big changeset.

One question:

- Any preferences? For example, we use `2 space chars` for left indentation. All our presets can be found [here](https://github.com/markdown-it/markdown-it/blob/master/.eslintrc)

For me the most simple way is to copy my linter configs. But i'm not sure you like those. Let me know what do you think.

**Comment by puzrin** [comment]
Done

**Comment by baudehlo** [comment]
Yeah honestly I will probably never work on this again, so make it what you work best with. Personally I'm old and can't see indents when they are two spaces, but I am happy to let you pick your own style here.

**Comment by puzrin** [comment]
Yeah, 2 spaces is not the best choice, but coding style standard for node (due lot of nested callbacks).

I'll probably will not work on this too :) . In long term users should/will migrate to webdriver api. But i hope this project is now in much more maintainable state and will not require changes next 1-2 years.
