### ISSUE TITLE
options.phantomPath -> options.path?

### ISSUE THREAD

**Issue by puzrin** [baudehlo/node-phantom-simple#58]
Now with SlimerJS option `phantomPath` looks strange. I suggest renaming it to something like `path` / `binary` / `execPath`. As usually, old style will be supported too, but will show deprecation message.

What do you think?

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple/commit/539dfe789e11545dac038a1db158191b848009c8 done

**Comment by fritx** [comment]
how to pass phantomjs command-line args http://phantomjs.org/api/command-line.html?

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple#createoptions-callback

**Comment by fritx** [comment]
Oops thanks. Just ignored it..
