### ISSUE TITLE
SlimerJS usage in headless (windowless) situations

### ISSUE THREAD

**Issue by MaarekElets** [baudehlo/node-phantom-simple#60]
Since there is the call for issues post 2.0 I wanted to raise this one. One of the major differences between SlimerJS and PhantomJS is the fact that SlimerJS is not headless and requires a windowing system of some sort to function. When run under Linux or FreeBSD there are situations where PhantomJS use will function without problem but SlimerJS will exit immediately because there is no X-Windows environment available to run Firefox/XulRunner in. SlimerJS suggests using [xvfb-run](http://manpages.ubuntu.com/manpages/lucid/man1/xvfb-run.1.html) in instances when under Linux (or OSX). 

This situation can be tested for by checking process.env.DISPLAY (BASH variable $DISPLAY) and if it's  empty/null then there isn't Display available to run in. 

There are three potential approaches I see to addressing this:

1. Document the requirement to using SlimerJS as the engine and make no code changes. It's likely this is a small use case (even though it did effect me, mine isn't a typical use scenario).

2. Document the requirement but also add a check to the DISPLAY variable when under Linux/FreeBSD/OSX  and throw a meaningful error on failure (or fall back on PhantomJS?).

3.  Add in a check on the DISPLAY variable and when null/empty use xvfb-run as the child-process command, pushing the SlimerJS command as the first argument (or second since we would probably want to use the -a switch to have xvfb-run automatically grab the first open server number).

  a. This would also require documentation to call out the dependency on xvfb and xvfb-run for the instances where headless operation is desired.

I'm willing to make the implementation attempt for option 3, but wanted to poll opinions before putting too much effort into it.

**Comment by puzrin** [comment]
IMHO if problem can be solved without code change, code should not be changed. I think, adding info to readme will be enougth. PR is welcome. Readme is not in perfect state.

**Comment by MaarekElets** [comment]
That's seems appropriate. I noticed a couple of (very) minor README errors so I'll add a note to the SlimerJS known issues section along with those and that should address it for the time being. If the need to implement it in becomes important enough we can always add it in later.
