### ISSUE TITLE
Any plans to implement page.clearMemoryCache() ?

### ISSUE THREAD

**Issue by RavenHursT** [baudehlo/node-phantom-simple#63]
Would love to see this capability exposed through the "bridge" :+1:

**Comment by RavenHursT** [comment]
Some context in the phantomjs project: https://github.com/ariya/phantomjs/commit/5768b705a019da719fa356fdbf370f3ea72b4c93

**Comment by RavenHursT** [comment]
lol.. looks like it's as simple as just adding it to the methods list on line 266 in node-phantom-simple.js..

**Comment by puzrin** [comment]
We've switched back to our projects. PR with test will be accepted.

**Comment by RavenHursT** [comment]
PR created.. https://github.com/baudehlo/node-phantom-simple/pull/64

**Comment by RavenHursT** [comment]
Oh.. I need a test for that?  arg..
