### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by winnemucca** [baudehlo/node-phantom-simple#66]
I used node-phantom simple before and loved it.  It seems to have changed a little over the past few months.  I am getting TypeError object is not a function.  However, it seems to be in my node_modules
I installed node phantom js as well.  Not sure what the problem is.
TypeError: object is not a function
    at /Users/stevenkauyedauty/projects/finalProject/moneyScrape/node_modules/node-phantom-simple/node-phantom-simple.js:203:20
    at ChildProcess.<anonymous> (/Users/stevenkauyedauty/projects/finalProject/moneyScrape/node_modules/node-phantom-simple/node-phantom-simple.js:93:10)
    at ChildProcess.g (events.js:180:16)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:808:12)

**Comment by puzrin** [comment]
No ideas. Need code example. All changes are recorded in changelog.

https://github.com/baudehlo/node-phantom-simple/blob/2.0.1/node-phantom-simple.js#L203 line from your error does not contain code. You do not seems to use latest version.

**Comment by winnemucca** [comment]
Nevermind, it was my generator.  I switched to a different one and had no problems.  Thanks
