### ISSUE TITLE
Long polling isn't cleaned up when exiting browsers

### ISSUE THREAD

**Issue by RavenHursT** [baudehlo/node-phantom-simple#69]
So I have this ExpressJS server that I'm using your awesome library to help manage PhantomJS.

This server maintains a pool of browsers for each request to come in and utilitize to visit URLs and extract data about the pages when they load.  Every so often, depending on the amount of times a given browser in the "pool" is used, we kill that browser, remove it from the pool and replace it w/ a new one.

This has all been working swimmingly (pun intended) up until I started throwing thousands of requests at it.  Over time (after around 15K requests or so) I noticed that the CPU would end up just pegging at 100% on the server.  I ended up narrowing it down to the long polling that node-phantom-simple(NPS) is using to perform IPC.

So I went ahead and created a simple pull request that essentially kills the long poll for a given browser if and when it's explicitly exited from: https://github.com/baudehlo/node-phantom-simple/pull/68

I'm sure there's a lot better ways to approach this (utilize phantom.killed?) but I needed something quick and dirty.. we have this running in production and I've now thrown 2X anything that I've thrown at it in the past and the CPU usages always come back down to normal after processing completes.

**Comment by johntitus** [comment]
One of the users of `node-horseman`, which depends on `node-phantom-simple`, ran into this issue: https://github.com/johntitus/node-horseman/issues/39

It appears to be based on this same issue, and doesn't require "thousands of requests".  Here's a very simple `node-phantom-simple` test that recreates it:

```js
var driver = require('node-phantom-simple');

driver.create(function (err, browser) {
	return browser.createPage(function (err, page) {
		return page.open("http://tilomitra.com/repository/screenscrape/ajax.html", function (err,status) {
			console.log("opened site? ", status);
			browser.exit();
		});
	});
});
```

The fix provided by @RavenHursT fixed the issue, both in the test script provided above and in `node-horseman`.

**Comment by puzrin** [comment]
Is fix ok? I will release then

**Comment by johntitus** [comment]
Yep, @Kirill89's fix resolves the issue in node-horseman.

**Comment by puzrin** [comment]
Released.

Enjoy :) !
