### ISSUE TITLE
abort in onResouceRequest

### ISSUE THREAD

**Issue by royalgarter** [baudehlo/node-phantom-simple#7]
Hi all,

I want to abort some ads resource on request but cannot call the abort() function.
Error: TypeError: Object #<Object> has no method 'abort'

Can someone give me an example that how to do it in page.onResourceRequested or do I miss understand something ?

**Comment by puzrin** [comment]
IMHO you can install your handler in phantom namespace via `setFn`, and have access to `.abort` there.

Can we close this?

**Comment by puzrin** [comment]
Closing - timed out. Seems nobody really need this. Use `setFn` if needed.

**Comment by maZahaca** [comment]
This is not working with Phantomjs 2. Could you provide an example?

**Comment by shawncreed** [comment]
@puzrin The problem is that when running via setFn, the request.abort() is available, however the function isn't actually executed when a resource is requested, so it's kind of useless.

**Comment by puzrin** [comment]
@shawncreed it worth to create new issue with details, this one is outdated IMHO.
