### ISSUE TITLE
Phantom crash handling?

### ISSUE THREAD

**Issue by fivepointseven** [baudehlo/node-phantom-simple#70]
Hi. Loving the project so far. One question.
Is there any way to catch phantom's crash (i.e. `Request() error evaluating evaluate() call: Error: connect ECONNREFUSED` and re-run it?

**Comment by puzrin** [comment]
All functions have callbacks. In most case, when you get error it worth to restart. See https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L553 and search "error" for possible cases.

**Comment by puzrin** [comment]
Closing?

**Comment by puzrin** [comment]
timed out
