### ISSUE TITLE
Move to a single handler (for SIGINT)

### ISSUE THREAD

**Issue by mehcode** [baudehlo/node-phantom-simple#72]
https://github.com/baudehlo/node-phantom-simple/blob/39515c695488165b8e0bf181bf4d29e09edcc0fb/node-phantom-simple.js#L127-L132

I'm running into the warning mentioned:

```
(node) warning: possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit.
```

**Comment by puzrin** [comment]
https://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n

Increase number of allowed listeners, that's not specific to this package.

**Comment by mehcode** [comment]
@puzrin This is specific to this package. See line 127 of the file I linked.

```
Note it's possible to blow up maxEventListeners doing this - consider moving to a single handler.
```

**Comment by puzrin** [comment]
@mehcode needs more details how to reproduce.

Probably, we don't release old handlers on browser close.

**Comment by puzrin** [comment]
Do you run multiple browsers in parallel?

Found more bugs on inspect #73. Seems this part should be polished.

**Comment by mehcode** [comment]
@puzrin 

At the moment I'm running quite a large number of browsers in parallel. It's not too bad but I'd prefer to run it under one browser process. I'm unsure of how to solve my race condition though so multiple browsers is how I've got it setup.

When a  request comes in (using redis pub/sub to accept requests), I check if a browser process exists and start it up if it doesn't. All subsequent requests then use that process. The problem comes if N requests come in at the beginning.

I suppose the real question is does it make sense to have 1000+ pages running on 1 process or 1000+ processes running a single page?

A solution that I could use is to create the browser process when the parent process starts up. That probably sounds like a thing I should do; apologies for making an issue about this. Another thing I should do is not try and do things like this at 03:00.

**Comment by puzrin** [comment]
https://github.com/caolan/async has method to limit max parallel run if you need. But anyway, you are right, it worth to limit number of subscribers for `process`.

I'd like to wait info from @baudehlo in second issue to clear all at once.

**Comment by puzrin** [comment]
Try fix from master.
