### ISSUE TITLE
Suspicious exit & uncaught handler

### ISSUE THREAD

**Issue by puzrin** [baudehlo/node-phantom-simple#73]
There are some strange legacy code (we didn't touched it at refactoring):

1. https://github.com/baudehlo/node-phantom-simple/blob/39515c695488165b8e0bf181bf4d29e09edcc0fb/node-phantom-simple.js#L122-L125 . It's responsibility of parent app to care about uncaught exceptions. Package should not write to console.
2. https://github.com/baudehlo/node-phantom-simple/blob/39515c695488165b8e0bf181bf4d29e09edcc0fb/node-phantom-simple.js#L122-L125 no need to force exit here. That can break paren'ts app logic.

@baudehlo do you have idea why this code was added? I think, it should be removed.

**Comment by puzrin** [comment]
@johntitus any objections about removal of that code? I plan to resolve all pending issues next week.

**Comment by johntitus** [comment]
I don't have any objections.
