### ISSUE TITLE
electron support?

### ISSUE THREAD

**Issue by puzrin** [baudehlo/node-phantom-simple#74]
https://github.com/atom/electron that could be interesting alternative (like SlimerJS) for PhantomJS - more fresh chromium engine.

Related:

- https://github.com/atom/electron/issues/228
- https://github.com/mafintosh/electron-prebuilt

PR welcome.

**Comment by fritx** [comment]
For example, what to do?

**Comment by johntitus** [comment]
Until it's truly headless, I don't think it's a good replacement for phantomjs. Perhaps a new project, node-electron-simple?

**Comment by puzrin** [comment]
@johntitus That's not full replacement, but alternative, like SlimerJS. Nobody force to use it. Phantom has very old chromium engine. Electron keeps it up to date. IMHO that's important for testing. Also i'm sure headless issue will be solved it near future.

**Comment by puzrin** [comment]
Closing - too significant api difference.
