### ISSUE TITLE
so many node-phantom-simple process are running

### ISSUE THREAD

**Issue by schitransh** [baudehlo/node-phantom-simple#75]
HI 

i am using node-phantom-simple in cluster environment.
after stopping complete service also, i am getting many process still lying (like below).
Please let me know how these process will stopped after finish there job?

oot     29946     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29947     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29956 29931  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29957 29930  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29962 29936  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29963 29946  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29964 29941  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29965     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29966     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29971 29947  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29976 29965  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29977 29966  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29978     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29983 29978  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29984     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29989 29984  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29990     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29991     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29992     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29993     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     29994     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30015     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30016 29990  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30019     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30020 29993  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30022 29994  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30023 29992  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30024     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30025 29991  0 10:37 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30026     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30027     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30028     1  0 10:37 ?        00:00:00 node ./node_modules/phantomjs/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30083 30026  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30086 30015  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30089 30027  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30097     1  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30129 30019  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30130     1  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30135 30024  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30149 30028  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30150     1  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30154     1  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/bridge.js
root     30158     1  0 10:38 ?        00:00:00 /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/phantomjs/lib/phantom/bin/phantomjs /idap/ReleaseBilling/ibps/ibps_scheduler/node_modules/nodeice/node_modules/node-phantom-simple/brid

Thanks
Chitransh

**Comment by Kirill89** [comment]
You should call `browser.exit();` for each instance before terminate your main process.

**Comment by schitransh** [comment]
Thanks for reply. i have used code like this. [in below]
 
Phantom = require("node-phantom-simple");

Phantom.create({path:'./node_modules/phantomjs/bin/phantomjs'},function(err,ph){
                        ph.createPage(function(err,page){
                                 page.set("viewportSize", { width: 2480, height: 3508 });
                                 page.open(tmpFileName, function(status) {
                                 page.render(options.output, function() {
                                        //Fs.unlink(tmpFileName);
                                        Fs.unlinkSync(tmpFileName);
                                        ph.exit();
                                        callback.call(this, arguments);
                                });
                            })
                        });
                });

I was doing ph.exit(); but there was many process lying. is it because we are sending bulk request in a second (approx 1000)?

Thanks
Chitransh

**Comment by puzrin** [comment]
@schitransh please format your messages properly https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown.

You should pass callback to `.exit(callback)`.

**Comment by puzrin** [comment]
Can we close it?

**Comment by schitransh** [comment]
@puzrin  Sorry for late reply.
Thanks for this suggestion. .exit(callback)
After done this it was working properly.

I am closing this issue from my side.

Thanks
Chitransh
