### ISSUE TITLE
Pass Header Contents to paperSize

### ISSUE THREAD

**Issue by johntitus** [baudehlo/node-phantom-simple#78]
Phantom seems to support passing a function to the contents attribute of its page.paperSize.header & footer.

http://phantomjs.org/api/webpage/property/paper-size.html

Is there some way to accomplish this in `node-phantom-simple`?

Initial attempt fails because phantom is undefined.  I tried just sending a function, but that didn't work either.  Setting the header.height works, but I can't get the contents to do anything.

```js
var driver = require('node-phantom-simple');

var paperSize = {
	format: 'A4',
	margin: "1cm",
	/* default header/footer for pages that don't have custom overwrites (see below) */
	header: {
		height: "1cm",
		contents: phantom.callback(function(pageNum, numPages) {
			if (pageNum == 1) {
				return "";
			}
			return "< h1>Header " + pageNum + " / " + numPages + "";
		})
	}
};

var path = 'out.pdf';

driver.create(function(err, browser) {
	return browser.createPage(function(err, page) {
		return page.open("http://www.google.com", function(err, status) {
			page.set('paperSize', paperSize, function() {
				page.render(path, {
					format: 'pdf',
					quality: '100'
				}, function() {
                  browser.exit();
					console.log('done');
				});
			});
		});
	});
});

**Comment by svvac** [comment]
Have a look at PRs #86 and #89, and discussion in #88

**Comment by puzrin** [comment]
Fixed by https://github.com/baudehlo/node-phantom-simple/commit/af88f55014ffc553282df26b146d4fa077edfb9f

**Comment by puzrin** [comment]
Please, update docs if needed.

**Comment by johntitus** [comment]
Looks good, thanks!
