### ISSUE TITLE
Undesirable side-effects on host module signal handling

### ISSUE THREAD

**Issue by svvac** [baudehlo/node-phantom-simple#81]
Hi,

I ran into this issue when using `node-phantom-simple` alongside Express. When running the following snippet:

```js
var phantom = require('node-phantom-simple');
var app = require('express')();

app.listen(0);
```

The node process stops handling `SIGINT` (i.e. Ctrl+C) and must manually be killed with `SIGQUIT` in order to exit. Removing the first line reverts back to the usual behavior.

Any hints ?

Env:
```
$ node -v
v4.1.1
$ npm -v
3.3.4
$ cat node_modules/node-phantom-simple/package.json | grep version
  "version": "2.0.5"
$ cat node_modules/express/package.json | grep version
  "version": "4.13.3"
$ uname -a
Linux lgce-arch3 4.2.1-1-ARCH #1 SMP PREEMPT Tue Sep 22 06:57:07 CEST 2015 x86_64 GNU/Linux
```

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L24

I guess, your app worked before, because you had no signal handlers at all, and some defaults were used. But you can't rely that nobody will use those handlers. Add your own with required behaviour.

**Comment by baudehlo** [comment]
Hmm, I would assume that would allow the default SIGINT handler to still
run though. If not, that's incorrect behaviour.

**Comment by puzrin** [comment]
I don't know why node works such way, but I think that's not driver issue.

https://github.com/baudehlo/node-phantom-simple/commit/f1859a07948b06f87fa5270c72318f9587f7d1e4 - here i removed some legacy handlers, but i'm 100% sure those were dirty kludges and should not be in this module.

**Comment by swordofpain** [comment]
OK, I guess Node runs `process.exit()` (or equivalent) when no `SIGINT` handler is present, but there's nothing on the doc about that. You have to admit that unexpectedly changing signal handling of a program is quite confusing for a library, even though there doesn't seem to be a way to work around this...

I suspect that this "signal proxy" is there to kill the phantom process when the main process is killed right ? In that case, why rely on signals rather than hooking to `process.on('exit', handler)`?

**Comment by puzrin** [comment]
> why rely on signals rather than hooking to process.on('exit', handler)?

See https://github.com/baudehlo/node-phantom-simple/commit/bf04f4dd2f8d795b239eb93c964a9a33d842bd6c and #72

**Comment by swordofpain** [comment]
I was more refering to [this](https://nodejs.org/api/process.html#process_event_exit)

**Comment by puzrin** [comment]
It's fired too late, program will exit before it transfer command to phantom.

**Comment by swordofpain** [comment]
That's right, my bad... So I guess there is no way in node to perform asynchronous cleanup without making proactive assumptions about the execution environment

**Comment by puzrin** [comment]
Closing?

**Comment by baudehlo** [comment]
Well I think maybe the SIGINT handler should also do process.exit(-1), no?

**Comment by puzrin** [comment]
@baudehlo since this module is not standalone app, it should not force any behaviour to upper level. For example, if i don't wish to react at SIGINT...

It's not cool that package now change default CTRL+C action, but IMHO nobody rely on node defaults in real world (except beginners :smile:). It's more safe to define SIGTERM / SIGINT / unhandledException handlers to have predictable behaviour.

**Comment by swordofpain** [comment]
I agree, doing `process.exit()` also a strong assumption. For instance, If the lib is used in a program that only terminates upon receiving two Ctrl+C in 500ms, you'll kill the phantom process on the first one... Or maybe the program choses not to exit on SIGINT, in that case `node-phantom-simple` would also exit too soon.

Basically you lack a way to perform async cleanup in the `exit` event (that would be the best option IMO). A decent workaround could be to exit the node process if there is no other event handler for SIGINT (using `[EventEmitter#listenerCount()](https://nodejs.org/api/events.html#events_emitter_listenercount_type)`). Or just expect the dev to explicitly perform the closing action, that wouldn't be a shocking expectation.

“Beginners” issues aside, breaking defaults by defaults is not really acceptable if you ask me.

**Comment by florian-rossiaud** [comment]
+1 @swordofpain

**Comment by puzrin** [comment]
I don't like magic in code. I would add SIGINT note to known issues in doc https://github.com/baudehlo/node-phantom-simple#known-issues.

**Comment by swordofpain** [comment]
Well, If you don't like magic, maybe the auto-quit should just go then ?

**Comment by baudehlo** [comment]
Maybe use this instead:
https://nodejs.org/docs/latest-v0.12.x/api/process.html#process_event_beforeexit

**Comment by swordofpain** [comment]
Or, as you said, add it to the known issues list and give a way to the dev to disable the magic feature. That would avoid breaking older code

**Comment by florian-rossiaud** [comment]
IMO you must let the developer close the instance of phantomjs like express does (via [net.Server#close](https://nodejs.org/api/net.html#net_server_close_callback) )

**Comment by puzrin** [comment]
@swordofpain we cleared a lot of legacy shit in 2.0.0 branch, and i don't like to return it back. May be it's better to just add SINGINT handler instead of improving the world :) ?

**Comment by swordofpain** [comment]
I'm not talking about reverting to old code, just to accept an option to not bind to `SIGINT`/`SIGTERM` (as the default would be to preserve compatibility if you wish to retain that feature), and let to the user the full responsibility of (explicitly) closing the processes. This approach would allow for:

  - less magic (you don't like it)
  - less assumptions (you don't like them)
  - less defaults silently broken (nobody likes them)

Best of both worlds ! I don't think it's `node-phantom-simple`'s responsibility to take care of process exits, since it's not a standalone app as you correctly pointed out.

**Comment by puzrin** [comment]
But we still have to do something with forked childs. It's not good to leave those after parent close.

**Comment by swordofpain** [comment]
Nor is it to close them if the parent doesn't indeed close (inc case of swallowed SIGINT for instance)

**Comment by baudehlo** [comment]
What about using .on('beforeExit') ?

**Comment by puzrin** [comment]
I think, we should care about closing phantom instances on process exit. That's important.

Can we use pings or monitor stdin/stdout state at bridge side? So, if bridge detects, that it's no longer mastered, it should kill itself.

**Comment by baudehlo** [comment]
Is my suggestion being ignored?

**Comment by puzrin** [comment]
@baudehlo i did not investigated it deep. But according to docs, this event is not guaranteed, for example on direct `process.exit()` calls.

**Comment by swordofpain** [comment]
Turning the problem around. I like the way you think. That solves the issue that `beforeExit` may not be called in certain circumstances, and the case of the master process being `SIGKILL`ed. We can still use it to do a close clean when we can. I can take a look at it tomorrow if you wish.

**Comment by puzrin** [comment]
@swordofpain That will help. I'd like to participate as minimum as possible - busy with other project. As you can see in history, after 2.0.0 i touch only simple cases and noticeable fuckups.

**Comment by svvac** [comment]
Alright, I'll keep you posted here. Cheers.

**Comment by svvac** [comment]
I think I've got something decent. One question though: can I count on the longpoll to perform a request every 500ms to the child process ? Or are there cases when it doesn't happen ? I don't want to perform an extra PING request at regular interval if it's done already.

**Comment by svvac** [comment]
My bad, it's not the case. We only poll if there's pending work.

**Comment by svvac** [comment]
See PR #87 for a working implementation.

**Comment by svvac** [comment]
May I suggest removing the `question` tag?
