### ISSUE TITLE
Deep-setting properties broken

### ISSUE THREAD

**Issue by svvac** [baudehlo/node-phantom-simple#90]
(Applies to phantomjs > 2, untested in earlier versions or with slimerjs)

Properties of the `page` object seem to be some kind of getter/setter properties that don't return a reference to the original object. As a result, deep-setting properties with `page#set()` (done in the bridge using the `lookup` helper) doesn't work because the original object is not modified.

See svvac/node-phantom-simple@a028fbaf (included in PR #89) for details and a fix.

**Comment by puzrin** [comment]
Could you do it as separate PR?

**Comment by Kirill89** [comment]
@svvac, could you please show an example of real case for this issue?
And about your PR, maybe you could also add test case?

**Comment by Kirill89** [comment]
@svvac, could you please show an example of real case for this issue?
And about your PR, maybe you could also add test case?

**Comment by puzrin** [comment]
Fixed by https://github.com/baudehlo/node-phantom-simple/commit/4c1e3e60e41433a6789821e81c4a44b7463595c7
