### ISSUE TITLE
page.evaluate problem

### ISSUE THREAD

**Issue by ortexx** [baudehlo/node-phantom-simple#91]
In official documentation api we can see:
`var title = page.evaluate(function(s) {
    return document.querySelector(s).innerText;
  }, 'title');
`
http://phantomjs.org/api/webpage/method/evaluate.html

1) This code is not working here. Function .evaluate requires callback when we write argument 'title'.
2) And page.evaluate always return undefined.

Can you fix this?

**Comment by puzrin** [comment]
Works as intended. See https://github.com/baudehlo/node-phantom-simple#usage start & known issues in readme.

**Comment by ortexx** [comment]
This "feature" makes the library almost useless in many cases.
I can not change anything in the context of the window, for example, during initialization(page.onInitialization, etc)

**Comment by puzrin** [comment]
There SetFn and so on. Anyway, if this lib is not ok for your tasks, nobody make you use it. There are no need to create issue about that.

**Comment by ortexx** [comment]
Your implementation of the bridge is the most comfortable right now. I have not only this feature.. setFn probably help me, thanks.

**Comment by BackSpaceTech** [comment]
This shouldn't be closed. The code supplied by ortexx doesn't work because node-phantom-simple does not pass values to evaluate.
e.g.
`                    page.evaluate ((tempSelector) ->
                      x = false
                      if $(tempSelector).length
                        x = true
                      return x
                    ), (err, result) ->
                      if err
                        console.log  err
                        return
                      else console.log 'Result: ' + result
                      return`
doesn't work,
but this does:
`                    page.evaluate ( ->
                      x = false
                      if $("#blahblah").length
                        x = true
                      return x
                    ), (err, result) ->
                      if err
                        console.log  err
                        return
                      else console.log 'Result: ' + result
                      return`
So how do you check if a selector exists if you can't pass it to evaluate?

**Comment by BackSpaceTech** [comment]
As pointed out by ortexx this doesn't work:

```javascript
var title = page.evaluate(function(s) 
{ return document.querySelector(s).innerText; }, 'title');
```
but this does:
```javascript
var title = page.evaluate(function() 
{ return document.querySelector("#selector").innerText; }, 'title');
```
In other words values cannot be passed to evaluate. 
Could the fix detailed [here ](http://stackoverflow.com/questions/9838119/pass-arguments-with-page-evaluate) be implemented?

**Comment by puzrin** [comment]
That's a low-level driver, not framework. It does only [most of] things allowed by phantom, with same [very similar] signatures. Additional sugar should be implemented outside.
