### ISSUE TITLE
node-phantom: onExit, also for node-phantom-simple

### ISSUE THREAD

**Issue by frankred** [baudehlo/node-phantom-simple#93]
Just migrating from node-phantom to node-phantom-simple because of cluster problems. 

Is there something like ```onExit``` to handle or recognize if the phantom process crashed or does node-phantom-simple handle a restart automatically itself?

**Comment by puzrin** [comment]
You have a `error` info in all callbacks, first argument. Just check it and recreate browser.

**Comment by frankred** [comment]
ok thanks
