### ISSUE TITLE
Set cookie

### ISSUE THREAD

**Issue by fabiomig** [baudehlo/node-phantom-simple#97]
Hello guys,

I'm trying to set a cookie from a file with this above code:

```javascript
driver.create({ path: require('phantomjs').path, parameters: {'load-images': false, 'ssl-protocol':'any'}}, function (err, browser) {
            
        return browser.createPage(function (err, page) {

            fs.readFile('./cookie.json', function read(err, data) {
            if (err) {
                throw err;
            }
                page.set('cookie', data);
            });

            return page.open('https://rebvoice.com/login', function (err, status) {

	        page.onLoadFinished = function(status){

	            page.evaluate(function () {

	                return window.location.href;
	                
	            }, function (err, result) {

	            		callback(result);
	            });
	        };
	    });

        });
```

console log shows this:

http.js:720
    throw new Error('Can\'t remove headers after they are sent.');
          ^
Error: Can't remove headers after they are sent.
    at ServerResponse.OutgoingMessage.removeHeader (http.js:720:11)
    at ServerResponse.send (/home/user/node_modules/express/lib/response.js:193:10)
    at /home/user/Betamax/betamaxscript.js:72:21
    at /home/user/Betamax/betamax-functions.js:20:16
    at /home/user/node_modules/node-phantom-simple/node-phantom-simple.js:56:11
    at poll_func (/home/user/node_modules/node-phantom-simple/node-phantom-simple.js:580:7)
    at /home/user/node_modules/node-phantom-simple/node-phantom-simple.js:52:7
    at ClientRequest.<anonymous> (/home/user/node_modules/node-phantom-simple/node-phantom-simple.js:497:11)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)

could someone give me a hand on this?

i can successfully read a cookie with page.get('cookie'  

Thanks in advance.
Fábio

**Comment by puzrin** [comment]
i guess you missed callback in page.set

**Comment by fabiomig** [comment]
Hi, puzrin
Tanks for your reply.

U mean i should set the cookie inside the callback?

**Comment by puzrin** [comment]
https://github.com/baudehlo/node-phantom-simple#usage look at first paragraph. I'd suggest to call .open() in callback of .set()

**Comment by fabiomig** [comment]
Hello again,
i've tryed call open in callback of set but im still being redirected to login page.

The callback status param of page.set('cookies'  gives me a success response.

What you think i should do next? i've tryied like 302302 ways :+1:

**Comment by puzrin** [comment]
I think the next is not driver-related. Try to make working script for phantomjs cli, then port it with use of this driver.

**Comment by joscha** [comment]
I ran into that issue before - cookies per page didn't work for me either - I had to set them on browser to make them work: https://github.com/crawlkit/crawlkit/blob/master/src/createPhantomPool.js#L29

**Comment by puzrin** [comment]
@joscha seems you are right. Our code in `navit` sets cookies via browser too:

- code: https://github.com/nodeca/navit/blob/master/lib/set.js#L14-L60
- test: https://github.com/nodeca/navit/blob/master/test/set.js#L92-L118

Seems a phantom issue, not driver one.

@fabiomig Closing?

**Comment by fabiomig** [comment]
Yes, i've solved in other way.

I've instanciated phantom on express start and then on routes i got a route /login that do the login and if i open another page, it uses the cookie file saved from login.
