### ISSUE TITLE
page.onResourceRequested gives empty object as second argument

### ISSUE THREAD

**Issue by Reewr** [baudehlo/node-phantom-simple#98]
I am currently in the process of creating a promise-wrapper for this library, instead of node-phantom.

In doing some tests I checked the arguments sent to the `onResourceRequested` event handler on the page object and I found that the `networkRequest` that the [PhantomJS docs](http://phantomjs.org/api/webpage/handler/on-resource-requested.html) specifies is an empty object.

This is most likely due to it containing functions. This object should, according to the documentation, contain three different functions:

> The `networkRequest` object contains these functions:
> 
> - `abort()` : aborts the current network request. Aborting the current network request will invoke onResourceError callback.
> - `changeUrl(newUrl)` : changes the current URL of the network request. By calling `networkRequest.changeUrl(newUrl)`, we can change the request url to the new url. This is an excellent and only way to provide alternative implementation of a remote resource. (see Example-2)
> - `setHeader(key, value)`

Reproduceable code:

```js
var driver = require('node-phantom-simple');
var util   = require('util');

driver.create(function(err, phantom) {
  phantom.createPage(function(err, page) {
    page.onResourceRequested = function(requestData, networkRequest) {
      console.log("NetworkRequest", util.inspect(networkRequest, {depth: null}));
    }

    page.open('http://www.google.com', function(err, status) {
      phantom.exit();
    });
  });
});
```

The output for the above script is the following:
```
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
NetworkRequest {}
```

I am currently not using the functionality of `onResourceRequested`, but I can see that it some day can become useful and it would be nice to have those functions available.

**Comment by baudehlo** [comment]
It would be really hard to support these due to the async nature of things. I can't even picture a way you could make them work. Can you?

**Comment by Reewr** [comment]
As far as I can understand from simple testing with PhantomJS, `onResourceRequested` only performs the request after it has returned. Therefore, if you were to include these functions as an option, you'd need to delay the function from returning until either:

1. Time has ran out
2. User has given the request go-head or aborted the request.

This would probably not play nice together with the internal web-server though, as you'd need to use a blocking-while or for-loop to do this, so, yeah. I guess I can see your problem. 

The problem became a lot more obvious to me when reading thoroughly through bridge.js and node-phantom-simple.js to see how you did the passing of events.

I didn't see an issue regarding this, so I thought I'd at least let you know.

**Comment by puzrin** [comment]
Situation is the same as with `onConfirm()` all sunc functions can work only if instelled to phantom namespace via `set`.

**Comment by freeqaz** [comment]
Is there any way that this can be hotfixed for somebody who wants to modify the network request? 

I'd like call `networkRequest.abort()` in one of my tests to prevent the call from being made.

Cheers!

**Comment by baudehlo** [comment]
No. Did you not understand my response?

**Comment by freeqaz** [comment]
I think that I understand if this is an async/sync mismatch. If Phantom is expecting the function to synchronously call `abort()`, but `node-phantom-simple` is async via the callback, then there being a mismatch there.

It would be nice if there was a way for Phantom to call through to our callback synchronously, but I'm not sure that's possible given the architecture. ¯\_(ツ)_/¯
